name: Flutter CI and Firebase Distribution

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.0'

    - name: Get Flutter Packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Setup Firebase CLI
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: firebase login --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Distribute to Firebase
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app flutter-15 --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
