name: Flutter CI and Firebase Distribution

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.0'

    - name: Get Flutter Packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: build/app/outputs/flutter-apk/app-release.apk
